1
urfu-2017/markup-task-4 pull request #16
Opened 2017-10-29 13:41 UTC by Xrias

2017-10-29 13:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-29 17:17 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-29 17:17 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-29 17:17 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-29 17:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-29 17:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-31 20:24 UTC, Grimfrid commented on index.css
> +a
Использовать просто теги не рекомендуется, так как если придется заверстать любую другую ссылку придется эти стили переопределять. Давай лучше что-то такое:
```
.cat-name 
{
...
}
```

Для остальных случаев тоже

2017-10-31 20:26 UTC, Grimfrid requested changes
Из общего:
1) Список на узком экране не влазит
![image](https://user-images.githubusercontent.com/3342089/32246981-7df066c2-be89-11e7-9cd0-7a93f0ed8490.png)

2) Фоточки котиков растягиваются, так не должно быть

3) Давай тут отступы добавим
![image](https://user-images.githubusercontent.com/3342089/32247084-dbe88a7a-be89-11e7-8a3a-6546de5576a7.png)
🍅

2017-11-05 10:52 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-05 11:38 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-07 07:04 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-07 07:04 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-07 07:06 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-07 07:35 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-07 07:43 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-07 07:46 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-07 08:26 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-07 09:38 UTC, closed without merging