Марков Евгений
urfu-2017/markup-task-4 pull request #22
Opened 2017-10-29 16:42 UTC by evgenymarkov

2017-10-29 16:43 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-30 11:59 UTC, vaseker commented on styles/index.css
> +    display: inline-block;
давай `display:block` и `max-width` для строчного режима.

2017-10-30 12:00 UTC, vaseker commented on styles/index.css
> +    src: url('../fonts/Yandex Sans Text-Regular.ttf');
откуда YSans выдрал ?)
эта версия не самая свежая)

2017-10-30 12:01 UTC, vaseker commented on styles/index.css
> +    width: 100%;
~~width:100%~~ -> `display: block;`

2017-10-30 12:08 UTC, vaseker commented on styles/settings.css
> +.input-view-list:checked ~ main .cat img,
.cat__photo

2017-10-30 12:08 UTC, vaseker commented on styles/settings.css
> +.input-view-tiles:checked ~ main .cat img,
.cat__photo

2017-10-30 12:08 UTC, vaseker commented on styles/settings.css
> +.input-view-tiles:checked ~ main .cat img
.cat__photo

2017-10-30 12:12 UTC, vaseker commented on styles/settings.css
> +    max-width: 90%;
нет поддержки изображений __любого__ размера. нормально отработают только изображения высотой 180px и выше. из-за этого решение немного не дотягивает до `extra`

2017-10-30 12:12 UTC, vaseker requested changes
🍅 
все взрывается на узком экране.
![2017-10-30 16-57-16](https://user-images.githubusercontent.com/1942271/32170206-8bf08d14-bd95-11e7-8276-7a6052885e37.png)


также нужно привести в порядок селекторы (особенно в settings)

2017-11-05 15:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-05 15:25 UTC, evgenymarkov commented on styles/index.css
> +    src: url('../fonts/Yandex Sans Text-Regular.ttf');
Легко выдирается с некоторых сайтов яндекса) Что в woff2, что в ttf. Но конкретно эту версию взял из презентаций для нашего курса на гитхабе.

2017-11-07 05:52 UTC, vaseker commented
🍅 
![2017-11-07 10-50-20](https://user-images.githubusercontent.com/1942271/32479013-ae98dadc-c3a9-11e7-96c4-d00db05f6a29.png)
![2017-11-07 10-49-31](https://user-images.githubusercontent.com/1942271/32479014-b1b0a844-c3a9-11e7-9e85-d6d063a942f4.png)

2017-11-07 09:06 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-07 09:08 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-07 09:13 UTC, evgenymarkov commented
Котов более не плющит в построчном режиме, в карточках проблему с Людвигом не смог воспроизвести ни в Chromium, ни в Firefox даже если 50x50 иконку помещать((
![screenshot from 2017-11-07 14-12-38](https://user-images.githubusercontent.com/16443248/32485603-d4b885e8-c3c5-11e7-895e-e6bb0e22cf78.png)
![screenshot from 2017-11-07 14-09-39](https://user-images.githubusercontent.com/16443248/32485619-e194423e-c3c5-11e7-9a9a-3a5ffbcdef23.png)

2017-11-07 09:24 UTC, vaseker commented
Людвигу я просто поставил высоту в 50px и он поместился в центр блока, а не прибился к низу.

![developer tools - https rawgit com evgenymarkov markup-task-4 master index html 2017-11-07 14-23-02](https://user-images.githubusercontent.com/1942271/32486067-58ec17e8-c3c7-11e7-9635-ceadba480b12.png)

2017-11-07 09:36 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-07 09:37 UTC, evgenymarkov commented
Прибил картинки к низу, была проблема из-за top: 20px

2017-11-07 12:02 UTC, vaseker commented
🍏

2017-11-07 12:02 UTC, closed without merging