lint
urfu-2017/markup-task-4 pull request #24
Opened 2017-10-29 18:40 UTC by Morkhod

2017-10-29 18:40 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-29 21:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-30 15:33 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-30 15:42 UTC, savichev-igor requested changes
В принципе очень хорошо, но именование классов странное, лучше их именовать через дефис, а camelCase оставить JS

Также много `div`'ов и мало семантических тэгов

🍅

2017-10-30 15:42 UTC, Savichev-Igor commented on index.html
> +        <div class="card">
Практически юбой `div` можно заменить на более семантический тэг

2017-10-30 15:42 UTC, Savichev-Igor commented on index.html
> +                <img src="images/cat1.jpg" alt="anothercat" class="image">
`alt` какой-то не очень дружелюбный, всё слитно :<

2017-10-30 15:42 UTC, Savichev-Igor commented on index.html
> +                <p class="price">Цена: 100 &#8381;
Если `&#8381;` - это перенос, то почему не <br>?

2017-10-30 15:42 UTC, Savichev-Igor commented on index.css
> +.rating.rating input:checked + label
`.rating.rating`?

2017-10-30 15:42 UTC, Savichev-Igor commented on index.css
> +    max-height: 250px;
Это плохо, когда коверкаем картинку по двум сторонам, видно, что пропорции ломается :<

2017-10-30 15:42 UTC, Savichev-Igor commented on index.css
> +    margin: 0 .5%;
Лишний пробел

2017-10-30 15:44 UTC, Savichev-Igor commented on index.html
> +                Is someone reading this??? Long text Long text
Хоть я тебя и понимаю, но давай лучше вставлять какие-нибудь осмысленные тексты, их всё равно читать приятнее)

2017-10-30 15:46 UTC, Savichev-Igor commented on index.html
> +                <a href="https://github.com/sameoldmadness">
👍

2017-10-30 18:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-31 09:31 UTC, Savichev-Igor commented on index.html
> +        <div class="card">
`article`?

2017-10-31 09:33 UTC, savichev-igor approved these changes

2017-10-31 09:33 UTC, Savichev-Igor commented
Хоть и остались `div`'ы, но в остальном стало всё сильно лучше!

Молодец!

⭐️

2017-10-31 09:33 UTC, closed without merging