Done.
urfu-2017/markup-task-4 pull request #38
Opened 2017-10-30 19:40 UTC by gus1234

2017-10-30 19:41 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-31 10:13 UTC, vaseker requested changes
🍅 
В целом, хорошо. Требуется только упрощение.

2017-10-31 10:13 UTC, vaseker commented on index.css
> +input[id='list']:checked ~ main label[for='list'] .icon,
селектор надо сделать проще

2017-10-31 10:13 UTC, vaseker commented on index.css
> +input[id='list']:checked ~ main .item .photo,
на `photo,info,description` нужно добавить общий класс

2017-10-31 10:13 UTC, vaseker commented on index.css
> +input[id='list']:checked ~ main label[for='list'] .icon,
#id все еще не проходит линтер?

2017-10-31 10:13 UTC, vaseker commented on index.css
> +.photo:hover > .bucket
тут ни к чему уточнение `>`

2017-10-31 10:13 UTC, vaseker commented on index.css
> +input[id^='set-']
![shta-babuska-01](https://user-images.githubusercontent.com/1942271/32218627-62803e80-be4d-11e7-9c06-db6474e7c51a.jpg)

надо на такие элементы навесить общий класс

2017-10-31 10:13 UTC, vaseker commented on index.css
> +    background-size: contain;
это уже опредено

2017-10-31 10:13 UTC, vaseker commented on index.css
> +    background: url(right_smile_cat.png) no-repeat;
background-image

2017-10-31 10:13 UTC, vaseker commented on index.css
> +    max-height: 225px;
~~255px~~ > 100%

2017-11-05 12:58 UTC, gus1234 commented on index.css
> +input[id='list']:checked ~ main label[for='list'] .icon,
да, если поменять на #id , то линтер дает ошибку
Unexpected id selector

2017-11-05 13:28 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-05 13:29 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-05 13:38 UTC, gus1234 commented
@vaseker fixed.

2017-11-07 10:55 UTC, gus1234 commented
@vaseker посмотрите , пожалуйста.

2017-11-07 16:54 UTC, vaseker commented
🍏

2017-11-07 16:54 UTC, closed without merging