готово
urfu-2017/markup-task-4 pull request #40
Opened 2017-10-30 19:49 UTC by HazipovVF

2017-10-30 19:49 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-31 18:17 UTC, msmirnov requested changes
* При наведении на карточку с котиком появляется рамка и все соседние карточки дёргаются, это плохо
* Чекбокс переключения вида страницы без подписи, на первый взгляд не понятно, что он делает
* При выводе списком всё разваливается, если сжать экран хотя бы до 1200px (описание уходит под фотографию)
* package-lock.json здесь не нужен

🍅

2017-10-31 18:17 UTC, msmirnov commented on index.css
> +    font-size: 15px;
При наведении вся страница дёргается, выглядит ужасающе

2017-10-31 18:17 UTC, msmirnov commented on index.html
> +
Не хватает семантики: всё на div'ах

2017-11-03 21:09 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-05 11:45 UTC, msmirnov approved these changes

2017-11-05 11:45 UTC, closed without merging