V2
urfu-2017/markup-task-4 pull request #46
Opened 2017-10-30 23:04 UTC by Rolyx2

2017-10-30 23:05 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-31 10:19 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-03 17:41 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-04 15:22 UTC, Mokoshka requested changes
- Предлагаю не обрезать описание для котиков совсем. Пусть карточки будут разные по размерам, но информация теряться не будет. 
- А еще некоторым котикам плохо. Было бы круто, если бы их так не плющило
![image](https://user-images.githubusercontent.com/14892550/32406636-b1b212c8-c19d-11e7-8824-c805f5020b12.png)
- При наведении на картинку часть зездочек остается 
![2017-11-04 19 51 53](https://user-images.githubusercontent.com/14892550/32406641-c85153f4-c19d-11e7-87a8-d53349201b9e.png)

2017-11-04 15:22 UTC, Mokoshka commented on index.html
> +                <img src="1.jpg" alt=""></div>
Пустой alt не стоит оставлять

2017-11-04 15:22 UTC, Mokoshka commented on index.html
> +        <div class="content">
Почему content? Совсем непонятный класс, который ни о чем не говорит. Можно же лучше придумать название

2017-11-04 15:22 UTC, Mokoshka commented on index.html
> +    <input id="line" type="checkbox">
Было бы круто, чтобы возле чекбокса была какая-то поясняющая надпись

2017-11-04 15:22 UTC, Mokoshka commented on index.css
> +    margin-top: 20px;
Объедини в одно правило

2017-11-04 15:22 UTC, Mokoshka commented on index.css
> +.name
Было бы круто, если бы имя обрезалось с многоточием в конце, так как сейчас непонятно что имя обрезано

2017-11-04 15:22 UTC, Mokoshka commented on index.css
> +input[id='line']:checked ~ .container .content .middle .name
А зачем так много классов в селекторе?

2017-11-04 15:22 UTC, Mokoshka commented on index.css
> +    height: auto;
Зачем?

2017-11-04 15:22 UTC, Mokoshka commented on index.css
> +input[id='line']:checked ~ .container .content .description
И здесь непонятно зачем столько классов в селекторе

2017-11-04 15:22 UTC, Mokoshka commented on index.css
> +input[id='line']:checked ~ .container .content .soHigh
Принято в названиях классов использовать дефиз: so-high

2017-11-04 15:22 UTC, Mokoshka commented on index.css
> +    height: 100%;
Высота в процентах работает только если у родителя задана высота. Здесь это правило ни на что не влияет

2017-11-04 15:22 UTC, Mokoshka commented on index.css
> +    max-height: auto;
А на это правило ругается браузер. Зачем ты его используешь?

2017-11-04 15:22 UTC, Mokoshka commented on index.css
> +    -o-transform: scale(1.8);
Принято указывать еще правило без префиксов

2017-11-04 15:22 UTC, Mokoshka commented on index.css
> +    margin-right: 50px;
Одним правилом лучше записать

2017-11-04 15:22 UTC, Mokoshka commented on index.css
> +.older-Price
Заглавная буква лишняя в названии класса

2017-11-04 15:22 UTC, Mokoshka commented on index.css
> +    float: right;
Но ведь можно и без float сверстать)

2017-11-06 00:38 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-06 19:05 UTC, Mokoshka requested changes
- Навожу на оценку больше и эффекта нет
![image](https://user-images.githubusercontent.com/14892550/32458541-8e07e1d8-c34e-11e7-821a-320ea78441e1.png)
- Вам еще не рассказывали, поэтому рекомендация на будущее, исправлять можно по желанию. Если используется много картинок в качестве background, например иконки, то их всех помещают на одно изображение - спрайт. А дальше позиционируют background таким образом, чтобы было нужное изображение. В этой задаче можно было не делить котиков пополам и не делать отдельное изображение для серых котиков. Можно было сделать одно изображение, а потом воспользоваться background-position

2017-11-06 19:05 UTC, Mokoshka commented on index.css
> +    overflow: hidden;
А зачем?

2017-11-07 04:48 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-07 09:26 UTC, Mokoshka commented
Нажимаю на оценку
![image](https://user-images.githubusercontent.com/14892550/32486110-7cbb7678-c3c7-11e7-8c7e-365c3d0091d1.png)
Получаю такой результат, а хотелось бы с половинкой
![image](https://user-images.githubusercontent.com/14892550/32486120-87f94ace-c3c7-11e7-87bb-2ec9b4c7c850.png)

2017-11-07 10:43 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-07 10:51 UTC, Mokoshka approved these changes

2017-11-07 10:52 UTC, closed without merging