Петрова Оля
urfu-2017/markup-task-4 pull request #51
Opened 2017-10-31 08:37 UTC by OlgaPetrova96

У меня дикие проблемы с отображением в виде списка. Как только я переношу куда-то checkbox, сразу всё перестает работать, поэтому он там находится. Косяк, знаю, но исправить не успеваю (да и не знаю как). А ещё для div после изображения кота не могу сделать отображение inline-blockом. Я как бы его делаю, но просто ничего не происходит (сейчас там ссылка и div, но раньше там были только divы и всё равно не работало).

2017-10-31 08:37 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-31 08:40 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-31 10:48 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-31 11:18 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-31 12:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-31 12:44 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-31 18:28 UTC, msmirnov requested changes
С выравниваниями всё не очень:
![image](https://user-images.githubusercontent.com/2646531/32241958-584c7dc0-be93-11e7-9958-6d081884d5df.png)

🍅

2017-10-31 18:28 UTC, msmirnov commented on index.css
> +.long-name
Странное название класса, имя же не обязательно длинное

2017-10-31 18:28 UTC, msmirnov commented on index.html
> +    <div class="div">
Непонятное название класса

2017-10-31 18:28 UTC, msmirnov commented on index.html
> +        <div class="child">
Класс child ни о чём не говорит

2017-10-31 18:28 UTC, msmirnov commented on index.html
> +        <div class="child">
Внутри этого div не хватает левого отступа, чтобы показать вложенность

2017-10-31 18:28 UTC, msmirnov commented on index.html
> +    <label for="ident"><img class="image" src="https://goo.gl/RspXuf" width="20" alt="list"></label>
Иконка прилипла к чекбоксу

2017-10-31 18:28 UTC, msmirnov commented on index.html
> +        <img src="https://goo.gl/PGGcKZ" alt="1 star"><br>
В некоторых карточках есть этот <br>, а в некоторых нет. Может быть, переносы как-то по-другому сделать?

2017-10-31 18:28 UTC, msmirnov commented on index.html
> +    </div>
Глобально: не хватает семантики, всё на div'ах. Параграфа для имени и категории неуместны.

2017-10-31 18:28 UTC, msmirnov commented on index.html
> +        <div class="child"><img class="img morph" src="https://goo.gl/f426qz" alt="фотография кота"></div>
Зачем на <img> два класса? Почему первый называется img?

2017-11-06 09:42 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-06 09:46 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-06 09:50 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-07 17:43 UTC, msmirnov approved these changes

2017-11-07 17:43 UTC, closed without merging