asdfasdf
urfu-2017/markup-task-4 pull request #52
Opened 2017-10-31 09:13 UTC by Admirallll

2017-10-31 09:13 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-06 16:28 UTC, savichev-igor requested changes
Всё выглядит хорошо, но кажется, что при отображении списком можно вытягивать контейнер на всю ширину, а картинку на всю высоту или хотя бы центровать по вертикали

А ещё мне кажется, что эффект при наведении на картинку лишний :<

![image](https://user-images.githubusercontent.com/7279995/32451606-0ae44c84-c339-11e7-8219-1f53947c2717.png)

🍅

2017-11-06 16:28 UTC, Savichev-Igor commented on index.html
> +    <div class="cat-cards">
Любой `div` можно заменить на более семантический тэг

2017-11-07 16:16 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-08 18:46 UTC, Savichev-Igor commented on index.html
> +    <main>
Нужно стараться всё-таки использовать классы, ибо на странице вполне могут встретиться в будущем ещё `main`ы и они уже должны будут иметь совершенно другие стили

2017-11-08 18:48 UTC, savichev-igor approved these changes
⭐️

2017-11-08 18:48 UTC, Savichev-Igor commented on index.html
> +    <main>
Нужно стараться всё-таки использовать классы, ибо на странице вполне могут встретиться в будущем ещё `main`ы и они уже должны будут иметь совершенно другие стили

2017-11-08 18:48 UTC, Savichev-Igor commented on index.html
>              <div class="cat-card-item cat-description">
`<p>...</p>`?

2017-11-08 18:48 UTC, closed without merging