1
urfu-2017/markup-task-4 pull request #58
Opened 2017-10-31 10:28 UTC by strota

2017-10-31 10:28 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-31 10:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-31 10:49 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-31 10:56 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-31 10:59 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-31 11:05 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-31 11:08 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-31 11:22 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-31 11:31 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-31 20:55 UTC, f0rmat1k requested changes
— Режим списка не доработан. Вид карточки котика должен меняться: фото слева, описание справа
— На большом экране режим грида должен вмещать больше, чем 3 элемента.
— Рейтинг котиков должен быть разный. Сейчас все 5 звезд.

2017-11-06 23:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-07 07:09 UTC, f0rmat1k approved these changes
> Реализовать эффекты при наведении на имя котика, фото, категорию, и плитку в целом  

Сейчас у тебя реализован эффект наведения только на имя. При этом он срабатывает на всей строке (т.е. даже в пустоте), а должен только на тексте. Т.к. это замечание единственное и некритичное, задачу принимаю.

2017-11-07 07:10 UTC, closed without merging