First try
urfu-2017/markup-task-4 pull request #66
Opened 2017-10-31 12:18 UTC by Tyashentin

2017-10-31 12:18 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-03 08:53 UTC, dotokoto requested changes
1) По макету имена котиков в карточках должны идти по одной линии
2) Список сверстан не по макету - должна идти картинка, в следующем столбике текст, в третьем - описание
3) Скакание верстки и размеров карточек при наведении надо исправить

2017-11-03 08:53 UTC, Dotokoto commented on index.css
> +    border: ridge#9b9797;
Пробела не хватает

2017-11-03 08:53 UTC, Dotokoto commented on index.css
> +    text-align-last: auto;
Для чего это правило?

2017-11-03 08:53 UTC, Dotokoto commented on index.css
> +    transition: max-width .5s, max-height .5s;
Сильно скачет вся верстка при анимации. Если анимируешь размер, то лучше сразу на это закладывать расстояние, чтобы всё не ехало. Хочется, чтобы при наведении были эффекты, но текст и остальные карточки оставались на месте

2017-11-03 08:53 UTC, Dotokoto commented
![2017-11-03 13-52-02](https://user-images.githubusercontent.com/8973726/32366075-642a9eda-c09e-11e7-854a-15ff10a31c83.png)
![2017-11-03 13-50-00](https://user-images.githubusercontent.com/8973726/32366078-67ab248a-c09e-11e7-922a-e76c292ee8a7.png)

2017-11-03 08:53 UTC, Dotokoto commented
:tomato:

2017-11-04 09:31 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-04 09:33 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-04 09:38 UTC, Tyashentin commented
@Dotokoto Имена теперь на одной линии, в списке по столбикам всё,  размеры карточек, текст не скачет. С изменением размера картинок чуть попарился, хотел посмотреть некоторые вещи из лекции, но на github слайды лекции не нашёл. Вместо изменения размеров поставил изменение прозрачности картинок.

2017-11-07 06:13 UTC, Dotokoto commented
Посмотрела еще раз, осталась пара мелких замечаний (на картинке). Раз сегодня дедлайн, то задачу принимаю, а замечания учти на будущее 
![2017-11-07 11-04-57](https://user-images.githubusercontent.com/8973726/32479646-a2d47e56-c3ac-11e7-86e0-bd7d9fd165cf.png)

2017-11-07 06:13 UTC, closed without merging