xxxx
urfu-2017/markup-task-4 pull request #67
Opened 2017-10-31 12:20 UTC by trszdev

2017-10-31 12:21 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-31 12:28 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-04 15:46 UTC, Mokoshka requested changes

2017-11-04 15:46 UTC, Mokoshka commented on index.css
> +p
Кажется, отступы у многих из этих элементов сделали бы верстку интереснее. Может стоит некоторые убрать?

2017-11-04 15:46 UTC, Mokoshka commented on index.css
> +    padding: 10px;
А зачем сначала обнулять padding, а затем снова проставлять?

2017-11-04 15:46 UTC, Mokoshka commented on index.css
> +    border: 1px solid pink;
Давай цвета hex-кодом задавать

2017-11-04 15:46 UTC, Mokoshka commented on index.html
> +                    <div class="description">
Но выглядит как параграф, почему div?

2017-11-04 15:46 UTC, Mokoshka commented on index.css
> +:checked ~ section article .title
У предыдущего селектора правила точно такие же, можно объединить

2017-11-06 13:11 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-06 19:23 UTC, Mokoshka requested changes

2017-11-06 19:23 UTC, Mokoshka commented on index.css
> +div,
У div по умолчанию margin и padding нулевые

2017-11-06 19:23 UTC, Mokoshka commented on index.css
> +    display: block;
header блочный элемент, это свойство лишнее

2017-11-13 08:44 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-13 08:45 UTC, trszdev commented on index.css
> +    display: block;
3626269

2017-11-13 08:45 UTC, trszdev commented on index.css
> +div,
3626269

2017-11-22 06:22 UTC, Mokoshka approved these changes

2017-11-22 06:22 UTC, closed without merging