Самая базовая реализация
urfu-2017/markup-task-4 pull request #68
Opened 2017-10-31 12:21 UTC by Edheltur

2017-10-31 12:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-05 07:37 UTC, Vittly requested changes
🍅 
назадавал вопросов

2017-11-05 07:37 UTC, Vittly commented on css/blocks/button.css
> +.btn
опять btn, давай `button` )

2017-11-05 07:37 UTC, Vittly commented on css/blocks/button.css
> +}
а помнишь мы делали модификаторы? давай также

2017-11-05 07:37 UTC, Vittly commented on css/blocks/card-list.css
> +    width: 100%;
мб просто `display: block` сделать?

2017-11-05 07:37 UTC, Vittly commented on css/blocks/card-list.css
> +    display: block;
вроде это лишнее, раз у тебя float

2017-11-05 07:37 UTC, Vittly commented on css/blocks/card-list.css
> +    margin-top: -100px;
это какое-то хакерство, давай сделаем без конкретного числа пикселей. Можно же было сделать `display: table/cell` как минимум и без всяких странных float-ов

2017-11-05 07:37 UTC, Vittly commented on css/blocks/card.css
> +}
это вроде лишний пассажир в этом файле - это не про блок "карточка"

2017-11-05 07:37 UTC, Vittly commented on css/blocks/card.css
> +    letter-spacing: normal;
а это зачем? это ж дефолт?

2017-11-05 07:37 UTC, Vittly commented on css/blocks/card.css
> +    margin: 0;
хм, а зачем занулять? откуда у него возьмется маржин?

2017-11-05 07:37 UTC, Vittly commented on css/blocks/card.css
> +    object-position: center;
знаешь ведь, что не везде работает. А знаешь как сделать, чтобы везде работало? Давай просто проговорим

2017-11-05 07:37 UTC, Vittly commented on css/blocks/card.css
> +    display: block;
вместе блочной ссылки лучше сделать `h2` и ссылку внутрь

2017-11-05 07:37 UTC, Vittly commented on css/blocks/card.css
> +    margin: .5em auto;
а для чего `auto` ? Не вижу эффетка

2017-11-05 07:37 UTC, Vittly commented on css/blocks/card.css
> +.card__price_old
бэму лучше `__price-old`

2017-11-05 07:37 UTC, Vittly commented on css/blocks/settings.css
> +}
не понял зачем эти стили

2017-11-05 07:37 UTC, Vittly commented on css/blocks/stars.css
> +    color: #ffc613;
а где увидеть этот цвет?

2017-11-05 07:37 UTC, Vittly commented on css/pages/index.css
> +    -webkit-font-smoothing: antialiased;
а зачем все это? можешь расписать?

2017-11-05 07:37 UTC, Vittly commented on css/blocks/stars.css
> +}
с этими "звездами" какая-то ерунда:
1- это не звезды - а радиобаттоны обернутые в label-ы. Давай сделаем звезды и давай уберем label-ы, если они не нужны
2- первый радиобаттон - это `value="10"` - что-то пошло не так? Давай сделаем 5 штук, а то 10 - это много
3- сначала ни у одного котика нет оценки
4- всякие `hover`-ы которые тут описаны кажется не работают. Давай или заставим это работать или выкосим лишнее

2017-11-05 18:28 UTC, Edheltur commented on css/pages/index.css
> +    -webkit-font-smoothing: antialiased;
https://medium.com/@MateMarschalko/improving-font-rendering-with-css-3383fc358cbc

У меня экран не очень высокого разрешения и подбешивает рендеринг шрифтов с изменением цвета.
![До](https://user-images.githubusercontent.com/4038984/32417808-d2b418a2-c280-11e7-8385-9fd8955e8bc5.png)

![После](https://user-images.githubusercontent.com/4038984/32417810-d4fccef6-c280-11e7-8812-bb8f63f3b532.png)

Обрати внимание на верхнюю часть букв.

2017-11-05 18:30 UTC, Edheltur commented on css/pages/index.css
> +    -webkit-font-smoothing: antialiased;
Сверху без этих свойств, снизу с ними. 
text-rendering: optimizeLegibility; Тоже нарыл в какой-то статье. В теории должен говорить браузеру "не экономь на кернинге"

2017-11-05 18:34 UTC, Edheltur commented on css/blocks/card.css
> +    object-position: center;
Если я правильно понимаю то с дополнительным дивом вокруг и background-image + background-size: cover; Попробую так.

2017-11-06 08:04 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-06 08:12 UTC, Edheltur commented on css/blocks/button.css
> +.btn
легаси, не успел поправить.

2017-11-06 08:12 UTC, Edheltur commented on css/blocks/settings.css
> +}
легаси

2017-11-06 08:13 UTC, Edheltur commented
🍏

2017-11-06 08:13 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-06 08:15 UTC, Edheltur commented on css/blocks/card-list.css
> +    width: 100%;
Все равно перебивать ширину через каскад. но inline-block тут лишний.

2017-11-06 08:15 UTC, Edheltur commented on css/blocks/card.css
> +    display: block;
Не совсем понял как это

2017-11-06 08:16 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-06 16:31 UTC, Vittly commented on css/blocks/card.css
> +    object-position: center;
да, все так. тут можно не делать

2017-11-06 16:31 UTC, Vittly commented on css/blocks/card.css
> +    display: block;
`<h2><a href="....">...</a></h2>`

2017-11-06 16:32 UTC, Vittly commented on css/blocks/button.css
> +.button-primary
давай использовать правила нейминга модификаторов: `.button_primary` или `.button--primary`

2017-11-06 16:33 UTC, Vittly commented on css/blocks/card-list.css
> +    margin-top: -100px;
мне не нравится решение через `-100px`

2017-11-06 16:33 UTC, Vittly commented on css/pages/index.css
> +    -webkit-font-smoothing: antialiased;
оки

2017-11-07 02:37 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-07 02:48 UTC, Edheltur commented on css/blocks/card-list.css
> +    margin-top: -100px;
Всё. Разобрался. А хак с отрицательным марджином - это, я так понимаю, очень древняя магия. Еще до display:table:cell

2017-11-07 03:01 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-07 06:57 UTC, Vittly commented on css/blocks/card.css
> +    display: block;
про "блок" - теперь лишнее правило

2017-11-07 06:59 UTC, Vittly commented on css/blocks/stars.css
> +.stars label:nth-child(4n-1):before
кажется, тут должно быть `2n+1`, так как `n` начинается с нуля и тут будет "-1"

2017-11-07 07:00 UTC, Vittly commented on css/blocks/stars.css
> +    -webkit-text-stroke-width: 0;
в целом тут какие-то проблемы, нельзя ткнуть в половину звезды, ховер работает, но полбалла нельзя поставить. Но раз тут без `extra`, то видимо ок

2017-11-07 07:02 UTC, Vittly requested changes
🍅 
table-cell надо дожать

2017-11-07 07:02 UTC, Vittly commented on css/blocks/card-list.css
> +}
тут получился какой-то хардкор, картинка - флоат, описание `cell`, а то что по середине просто болтается как попало. Давай всем сделаем `table-cell`, а "средних ребят" обернем в дополнительный див, чтобы и у них была ячейка

2017-11-07 07:52 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-07 08:01 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-07 08:04 UTC, Vittly approved these changes

2017-11-07 08:05 UTC, Vittly commented
хорошо!

2017-11-07 08:05 UTC, closed without merging