Готово
urfu-2017/markup-task-4 pull request #76
Opened 2017-11-23 10:20 UTC by RomanDengin

Из звёздочки только выравнивание картинок по нижнему краю реализовано

2017-11-23 10:20 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-03 16:36 UTC, savichev-igor requested changes
Нету эффекта при наведении никакого :<

Ещё я бы `border` убрал при отображении списком

🍅

2017-12-03 16:36 UTC, Savichev-Igor commented on index.css
> +    position: inherit;
Кажется, что это ни на что не влияет

2017-12-03 16:36 UTC, Savichev-Igor commented on index.css
> +    height: auto;
И это

2017-12-03 16:36 UTC, Savichev-Igor commented on index.css
> +    display: table;
Табличная вёрстка должна использоваться только при вёрстке таблиц :<

2017-12-03 16:36 UTC, Savichev-Igor commented on index.css
> +    display: table-cell;
Аналогично

2017-12-03 16:36 UTC, Savichev-Igor commented on index.css
> +    display: table-cell;
:<

2017-12-03 16:36 UTC, Savichev-Igor commented on index.html
> +            <div class="desc">
`<p>`?

2017-12-03 16:36 UTC, Savichev-Igor commented on index.html
> +                <p class="cap">
Это больше на заголовки похоже

2017-12-03 16:36 UTC, Savichev-Igor commented on index.html
> +            <div class="card">
`<article>`?

2017-12-03 16:36 UTC, Savichev-Igor commented on index.html
> +
Зачем эти пустые строки?

2017-12-09 22:51 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-09 23:27 UTC, RomanDengin commented
:greenapple:
Поправил

2017-12-10 09:49 UTC, savichev-igor approved these changes

2017-12-10 09:49 UTC, closed without merging